Check that the tip of a ref matches latest corresponding RSL entry
gittuf/gittuf pull request #201
Opened 2023-11-22 10:19 UTC by adityasaky

This updates the repository package to check that the current state of the tested ref matches the latest RSL entry.

2023-11-30 14:13 UTC, wlynch requested changes
LGTM! We should add some more godoc though. 🙏

2023-11-30 14:13 UTC, wlynch commented on internal/policy/verify.go
>  // using the latest policy.
Update godoc to explain what the returned hash value represents.

2023-11-30 14:13 UTC, wlynch commented on internal/repository/verify.go
> +var ErrRefStateDoesNotMatchRSL = errors.New("Git reference's current state does not match latest RSL entry") //nolint:stylecheck
Add godoc explaining what this means / how a repo can get into this state / how to resolve?

2023-12-03 05:15 UTC, adityasaky commented
Done!

2023-12-11 16:57 UTC, wlynch approved these changes

2023-12-11 16:57 UTC, merged