Enhance Documentation - Design
gittuf/gittuf pull request #226
Opened 2023-12-16 00:44 UTC by naveensrinivasan

1. Added a visual representation of a Git repository structure.
2. Expanded the definition of 'Actors' in the context of a Git repository and the gittuf system.
3. Introduced a new term 'State' and provided a detailed explanation and example of it.

2023-12-18 14:34 UTC, adityasaky requested changes
A few minor nits aside, I think this is great to add to the doc. Thanks!

2023-12-18 14:34 UTC, adityasaky commented on docs/design-document.md
> +|   |   |-- v1.0 (refers to commit B)
Can you rename `commits` to be `objects` below and include a `v1.0` tag object that in turn refers to commit `B`?

2023-12-18 14:34 UTC, adityasaky commented on docs/design-document.md
> +|   |   |-- v1.0 (refers to commit B)
this message here would then say `refers to tag v1.0`

2023-12-18 14:34 UTC, adityasaky commented on docs/design-document.md
> +The term "State" refers to the latest values or conditions of the tracked references
```suggestion

The term "State" refers to the latest values or conditions of the tracked references 
```

2023-12-18 14:34 UTC, adityasaky commented on docs/design-document.md
> +In a Git repository, an 'actor' is any user who makes changes to the repository.
nit: can you wrap to 80 cols?

2023-12-18 14:34 UTC, adityasaky commented on docs/design-document.md
> +#### Example:
```suggestion
#### Example

```

2023-12-18 14:34 UTC, adityasaky commented on docs/design-document.md
> +In a Git repository, an 'actor' is any user who makes changes to the repository.
also nit: trailing whitespaces in a bunch of these lines.

2023-12-18 22:25 UTC, adityasaky commented
@naveensrinivasan I took the liberty of pushing 56fc7f2abb9c7ffa84077cc16d3e176c7793fdee to fix some col length / trailing whitespaces to clarify what my editor was flagging. Could you fetch that commit and squash all the commits (don't worry about co-authored-by etc for this one btw)? Thanks!

2023-12-18 22:26 UTC, adityasaky commented
On a side note, we should probably lint the markdown files as well in CI :thinking:

2023-12-19 01:52 UTC, JustinCappos reviewed
Looks pretty good!  Just a few more things need to be clarified.  I'm happy to discuss on slack or elsewhere if my feedback isn't clear.

2023-12-19 01:52 UTC, JustinCappos commented on docs/design-document.md
> +the updates pertinent to each individual reference, ensuring a focused review of
Can you clarify this sentence?  Especially what you mean by "attention is given specifically to
the updates pertinent to each individual reference,"

2023-12-19 01:52 UTC, JustinCappos commented on docs/design-document.md
> +main branch might be defined by the latest commit, say Commit A. Similarly, the
What do you mean by "defined"?

2023-12-19 01:52 UTC, JustinCappos commented on docs/design-document.md
> +Commit A, while for the feature branch, up to Commit B.  This method allows for
I'm not exactly sure what you're proposing / saying here.  What method do you mean and how does this vary from git?

2024-02-12 18:34 UTC, JustinCappos approved these changes

2024-02-12 18:37 UTC, adityasaky commented
@naveensrinivasan I pushed some updates based on Justin's feedback. Thank you for the changes here, I think the actor text clarification + the .git structure in particular is helpful.

2024-02-12 18:38 UTC, adityasaky approved these changes

2024-02-12 18:38 UTC, merged